using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CursorControler : MonoBehaviour
{
    public Texture2D cursor;
    public Texture2D cursorClicked;

    private CursorControls controls;

    // Start is called before the first frame update
    void Awake()
    {
        controls = new CursorControls();
        ChangeCursor(cursor);
        Cursor.lockState = CursorLockMode.Confined; 
    }

    private void OnEnable(){
        controls.Enable();
    }

    private void OnDisable(){
        controls.Disable();
    }

    private void Start(){
        controls.Mouse.Click.started += _ => StartedClick();
        controls.Mouse.Click.performed  += _ => EndedClick();
    }

    private void StartedClick(){
        ChangeCursor(cursorClicked);
    }

    private void EndedClick(){
        ChangeCursor(cursor);
    }

    private void ChangeCursor(Texture2D cursorType){
        Vector2 hotspot = new Vector2(cursorType.width/2, cursorType.height/2);
        Cursor.SetCursor(cursorType, hotspot, CursorMode.Auto);
    }

}
